---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdr-demo
  namespace: ${workspaceNamespace}
  labels:
    app: mdr-demo-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mdr-demo-nginx
  template:
    metadata:
      labels:
        app: mdr-demo-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.31-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html/mdr-demo
          readOnly: true
      volumes:
      - name: html-content
        configMap:
          name: mdr-demo-index-page
          items:
          - key: index.html
            path: index.html