---
apiVersion: v1
kind: Service
metadata:
  name: mdr-demo
  namespace: ${workspaceNamespace}
spec:
  type: ClusterIP
  selector:
    app: mdr-demo-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80